# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tunnee < Formula
  desc "Expose your local services to the internet."
  homepage "https://tunnee.com"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.tunnee.com/cli/0.4.0/tunnee_0.4.0_darwin_x86_64.tar.gz"
      sha256 "41bcc324dc3ba723373f8153502f9da04a057ff018dd994cbd01d38e6366bea5"

      define_method(:install) do
        bin.install "tunnee"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.tunnee.com/cli/0.4.0/tunnee_0.4.0_darwin_arm64.tar.gz"
      sha256 "d860628b1c1fe75215b2d373bbbdd822bc8d82c6ab551453bbd0c2bb138cf53b"

      define_method(:install) do
        bin.install "tunnee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://downloads.tunnee.com/cli/0.4.0/tunnee_0.4.0_linux_x86_64.tar.gz"
      sha256 "d7a1977fca05e6d7129abef507c303611d1eba5429c81f247bd0535439606baa"
      define_method(:install) do
        bin.install "tunnee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://downloads.tunnee.com/cli/0.4.0/tunnee_0.4.0_linux_arm64.tar.gz"
      sha256 "2536fe59664b47d92994e4efbd4440bbbca29f32145dfc182996dcd1563de89f"
      define_method(:install) do
        bin.install "tunnee"
      end
    end
  end

  test do
    system "#{bin}/tunnee", "--version"
  end
end
