# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tunnee < Formula
  desc "Expose your local services to the internet."
  homepage "https://tunnee.com"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.tunnee.com/cli/1.0.0/tunnee_1.0.0_darwin_x86_64.tar.gz"
      sha256 "0d11ebf74457d193e25e2da94a31978df800667e4e9188926c855ca3d635759e"

      define_method(:install) do
        bin.install "tunnee"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.tunnee.com/cli/1.0.0/tunnee_1.0.0_darwin_arm64.tar.gz"
      sha256 "3c0797d925e967ad288858319085914b0ff08eb34b2442d4fb054f6e842a6257"

      define_method(:install) do
        bin.install "tunnee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://downloads.tunnee.com/cli/1.0.0/tunnee_1.0.0_linux_x86_64.tar.gz"
      sha256 "8afd14acc69013e055fbc413060e871bc685ddf8c409b45354820cc84f3ec1a5"
      define_method(:install) do
        bin.install "tunnee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://downloads.tunnee.com/cli/1.0.0/tunnee_1.0.0_linux_arm64.tar.gz"
      sha256 "43e2fea3bb30ea2aa4e51f2185227ffe2bd31db907ca6b0dad232f2185896fa8"
      define_method(:install) do
        bin.install "tunnee"
      end
    end
  end

  test do
    system "#{bin}/tunnee", "--version"
  end
end
